CC = g++
CFLAGS = -Wall -Wextra -pedantic -std=c++11

all: add2PB findPhone

add2PB: add2PB.cpp
	$(CC) $(CFLAGS) -o add2PB add2PB.cpp

findPhone: findPhone.cpp
	$(CC) $(CFLAGS) -o findPhone findPhone.cpp

clean:
	rm -f add2PB findPhone
